version: '3'
services:
  tns:
    build:
      context: .
    image: zerosuxx/nativescript:latest
    volumes:
    - ./:/root/project
    - /dev/bus/usb:/dev/bus/usb
    privileged: true
    network_mode: host
