version: '2'
services:
  tns:
    build:
      context: .
      args:
        ANDROID_SYSTEM_PACKAGE_VERSION: "26"
        ANDROID_BUILD_TOOLS_PACKAGE_VERSION: "26.0.2"
    privileged: true
    network_mode: host
    working_dir: /home/tns
    volumes:
      - ./:/home/tns
